name: newsapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  get: 4.6.5
  url_launcher: ^6.0.20
  error_message:
    git: https://github.com/TamilKannanCV/error_message.git
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_web: ^0.2.2+1
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_native_splash: ^2.1.2+1

flutter_native_splash:
  android: true
  ios: true
  web: true
  image: assets/images/logo.png
  color: "#FFFFFF"
  color_dark: "#1B1B1B"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
